language: elixir
elixir:
  - 1.6.6
addons:
  postgresql: '9.4'
env:
  MIX_ENV: test
  DOCKUP_BACKEND: fake
services:
  - postgresql
before_script:
  - cp apps/dockup_ui/config/travis.exs apps/dockup_ui/config/test.exs
  - mix do deps.get, compile --warnings-as-errors, ecto.create, ecto.migrate
