db:
  image: postgres:9.4.4
  environment:
    - POSTGRES_PASSWORD=secret
    - POSTGRES_USER=user
web:
  build: .
  dockerfile: Dockerfile.chatops
  command: mix phoenix.server
  ports:
    - "4000"
